### ISSUE TITLE
PurePerms/Chat Support

### ISSUE THREAD

**Issue by thicksunny** [jaylac2000/StaffStatus#5]
I recommend adding PurePerms/Chat support, so users can identify staff as a certain group rather than usernames.

**Comment by jaylac2000** [comment]
if people really want that, they can use {prefix} is pure chat and use /setprefix

**Comment by jaylac2000** [comment]
or you mean like

OWNER: 
- jaylac2000
ADMIN:
- admindude55
MOD:
- modguy65
HELPER: 
- the helping guy 1128

**Comment by thicksunny** [comment]
No, I mean in the config, to get rid of having to add usernames everytime, just make it so they only have to add the purechat group

**Comment by jaylac2000** [comment]
well, than they cannot choose which order which player goes in, my self i like to choose which order which player is, so for now i wont consider this, unless others suggest it, or someone makes a PR giving multiple options on how the list is setup
